### ISSUE TITLE
Velocity commands not executed correctly in ground_truth estimation position type

### ISSUE THREAD

**Issue by itaouil** [graiola/wolf-setup#11]
Hi,

It seems like the behavior of the controller changes when I set the **estimation_position_type** in the param to **ground_truth**.

In particular, when I set a high velocity (say for example 0.9) and switch back to 0.2 for example the robot does not actually execute that lower velocity, but instead it seems to stomp on the spot, as if the velocity set is 0.0.

Here is a small video demonstrating the behavior.

https://user-images.githubusercontent.com/17275225/146845563-9ab8392b-3e35-48a0-8275-814f82f57765.mp4

**The same behavior does not happen when the estimation position type is set to estimated_z btw....**.

Any idea on what is causing such an issue? Could it be something related to the IMU sensor?

**Comment by graiola** [comment]
Hi @itaouil , today I am travelling back home. I am going to give a look at the issue asap :)

**Comment by itaouil** [comment]
Thanks :)

Safe travel!

**Comment by graiola** [comment]
Hi @itaouil , the video doesn't show up, it says that can not be played because the file is corrupted.

**Comment by itaouil** [comment]
> Hi @itaouil , the video doesn't show up, it says that can not be played because the file is corrupted.

I uploaded it to drive :)

https://drive.google.com/file/d/1iK-sqa3j57DMBnQW1WlYdTuaUH-kaQ-Y/view?usp=sharing

**Comment by graiola** [comment]
It seems there is a bug when using the ground_truth. Did you have this problem before?

**Comment by itaouil** [comment]
I actually never tried the **ground_truth** before. I always used the **estimated_z**.

**Comment by graiola** [comment]
I think i solved the bug, I am building the debians now....

updated!

**Comment by itaouil** [comment]
I will try it now and update you asap!

**Comment by itaouil** [comment]
Hi,

I gave it a try. It seems that the bug is solved now :).

While trying I noticed couple of behaviors that still persist. For example the shuffling of the support feet in the back (along with some weird posture)

Here is a couple videos demonstrating it (especially the second video link):

https://drive.google.com/file/d/1uqx_RToWp3JJriSPXZY_aZ19Pkbo66x9/view?usp=sharing
https://drive.google.com/file/d/1sNlOdC7eqapSEZWqw2YHsWuSWsv3QjRr/view?usp=sharing

**Comment by graiola** [comment]
does it happen when using the estimation?

**Comment by itaouil** [comment]
Yes...

Here is a video showcasing the same sort of shuffling behavior while using **estimated_z**:

https://drive.google.com/file/d/1iXTlTBDZdoICsMvYvvEkjpKiik99PAsX/view?usp=sharing

But I remember it quite distinctly not being the case before though.

---

Also...

Was something changed in the terrain estimation and attitude control :)? As I am not able to obtain the same results in climbing up and down the stairs as before with the AlienGo.

For example this is what always happens right now: 

https://drive.google.com/file/d/1vFOuyofax-AGkbqvw2kgO0hx1W63Al7I/view?usp=sharing

**Comment by graiola** [comment]
Tomorrow I am going to investigate...

**Comment by graiola** [comment]
I made a quick revert to an older commit and generated the debians. You can try and see if it solves the issue on your side.
On my computer is working fine (note that I am using a joypad). Let me know :)

**Comment by itaouil** [comment]
The shuffling still persists, and the climb up with the stairs still fails with the same slope as the video I posted some time ago.

Unfortunately I cannot even cross-check with my other PC which has the previous working version of the debians whether the same behavior was there back then (although I am 90% sure the shuffling was not as present as right now if not at all) :).

But I will be able to do so on the 1st of January once I am back in Germany :).

**Comment by itaouil** [comment]
Anyway, the original problem was solved so I will close this issue.

Thanks for your help even during the holidays. Much appreciated :).
