### ISSUE TITLE
Create ros service for separate leg or body

### ISSUE THREAD

**Issue by elpimous** [graiola/wolf-setup#17]
In a near futur, will you create a ros topic to move isolated foot, or move/rotate body only ?

Working on a python choregraphie app, with sliders (calling robot parts moving), a music, and sound waveform with metronome for tempo, rec instant position, and player.  Idea is to record a music choregraphie, but need to be able to move separate legs, and move/rotate body. Well, use my robot like a puppet

anything like x,y,z position for end_leg,  and x,y,z,rot_x,rot_y,rot_z for body

I could, too, record different sequences, where my quadruped could simulate life, between some walks.

It would be very cool, Thanks
Vincent

**Comment by graiola** [comment]
The idea would be to create a plugin system to load different behaviors in the controller. Right now the SoT works only in conjunction with the walking pattern generator presented in the paper.

**Comment by elpimous** [comment]
Humm, it was quite easier, in my head..
Next TODO (in my dreams)
