### ISSUE TITLE
Can't access wolf_controller under rqt_reconfigure, with new xacro robot

### ISSUE THREAD

**Issue by elpimous** [graiola/wolf-setup#19]
Hello the team, i made the ylo2 package, copying your aliengo_description one
robot is ok under rviz (sizes, rotations, inertia)
Don't see any errors in terminal : https://pastebin.com/SzhDDbvU
https://ibb.co/ByQbhSm
the soft launchs ok, i can see gazebo params in rqt_reconfigure, but i don't see the ylo2/wolf_controller inside it, even with refreshs

Could it be a startup pose positions problem ? Where could i search for errors ?

**Comment by graiola** [comment]
Hi @elpimous , there is an error with the ros controller manager, `Controller Spawner couldn't find the expected controller_manager ROS interface.` 
Do you have the latest packages installed? If not, please run the installation again or get them with the script `wolf-setup/support/get_debians.sh`, you will find them in the folder `wolf-setup/debs/devel/`.

**Comment by elpimous** [comment]
Hey, Gennaro, what a quick answer... 
Your new install.sh is nice (logo). Well, installed, ok.
Same problem. It could be the fault of my initial pose... Do you have an imu check before starting the wolf controller ?

**Comment by elpimous** [comment]
[ylo2_description.zip](https://github.com/graiola/wolf-setup/files/7959179/ylo2_description.zip)
Here is my robot_description.... if you want to test..

**Comment by graiola** [comment]
Yes, I would be very happy to give it a spin asap :)
Also, feel free to open a pull request on https://github.com/graiola/wolf_descriptions with the new robot, so that it would be easier for both of us to work on it.

**Comment by elpimous** [comment]
I'll do it for sure..
thanks

**Comment by graiola** [comment]
Hey @elpimous , I fixed the issue, there was an `aliengo` in the urdf. I was able to spawn the controller and to move the robot around but the controller needs some tuning. You can get the fix in the `ylo2` branch https://github.com/graiola/wolf_descriptions/tree/ylo2

**Comment by elpimous** [comment]
Very good job, Gennaro... Working on it.
Thank you so much.
Vicent

**Comment by elpimous** [comment]
@graiola , I just sent a pull request (first time for me !) Hope it worked
