### ISSUE TITLE
error on catkin_make, with sensors_description

### ISSUE THREAD

**Issue by elpimous** [graiola/wolf-setup#21]
Hello, here is the pastebin of the terminal...
https://pastebin.com/m3jAT87t
Any idea ?

**Comment by graiola** [comment]
The error is caused by the fact that your compiler is treating warnings as errors `all warnings being treated as errors`.
You have to set the compiler to ignore the warnings. Btw I am going to fix the warnings in the meanwhile.

**Comment by graiola** [comment]
Fixed the warnings, I am going to close that.

**Comment by elpimous** [comment]
Working great. Thanks for reactivity
