### ISSUE TITLE
Could not load library (Poco exception = libsrdfdom.so.0.6.2: cannot open shared object file: No such file or directory)

### ISSUE THREAD

**Issue by elpimous** [graiola/wolf-setup#25]
hello, this error occured after install on noetic (ubuntu 20.04)
No errors at install, neither catkin_make

[FATAL] [1644784871.955292655]: Failed to create robot simulation interface loader: Failed to load library /opt/ros/noetic/lib/libwolf_hw_sim.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libsrdfdom.so.0.6.2: cannot open shared object file: No such file or directory)

An idea?

**Comment by graiola** [comment]
did you run the install.sh script?

**Comment by EnricoMingo** [comment]
Looks like you are missing libsrdfdom.so

**Comment by elpimous** [comment]
Hello. Yes I did. /install.sh.I'll restart tonight... Envoyé depuis mon téléphone Huawei-------- Message original --------De : Enrico Mingo Hoffman ***@***.***>Date : dim. 13 févr. 2022 à 23:52À : graiola/wolf-setup ***@***.***>Cc : FOUCAULT Vincent ***@***.***>, Author ***@***.***>Objet : Re: [graiola/wolf-setup] Could not load library (Poco exception = libsrdfdom.so.0.6.2: cannot open shared object file: No such file or directory) (Issue #25)

Looks like you are missing libsrdfdom.so

**Comment by graiola** [comment]
it looks like you don't have ros-noetic-srdfdom or you have a different version.
Can you post here the output of:

`sudo dpkg -l | grep ros-noetic-srdfdom`

**Comment by elpimous** [comment]
Souhait=inconnU/Installé/suppRimé/Purgé/H=à garder
| État=Non/Installé/fichier-Config/dépaqUeté/échec-conFig/H=semi-installé/W=attend-traitement-déclenchements
|/ Err?=(aucune)/besoin Réinstallation (État,Err: majuscule=mauvais)
||/ Nom                Version                      Architecture Description
+++-==================-============================-============-====================================================
ii  grep               3.4-1                        amd64        GNU grep, egrep and fgrep
ii  ros-noetic-srdfdom 0.6.3-1focal.20220201.004735 amd64        Parser for Semantic Robot Description Format (SRDF).

**Comment by elpimous** [comment]
I installed ros-noetic-full, rosdep update, sources... and ./install.sh until the end.
deleted wolf-setup dir, and reinstalled it : same error.

reinstalled SRDF : `sudo apt-get install --reinstall ros-noetic-srdfdom`

roslaunch wolf_controller wolf_controller_bringup.launch input_device:=keyboard
`
FATAL] [1644841690.602021456]: Failed to create robot simulation interface loader: Failed to load library /opt/ros/noetic/lib/libwolf_hw_sim.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libsrdfdom.so.0.6.2: cannot open shared object file: No such file or directory)`


https://pastebin.com/nMduKCr0

**Comment by graiola** [comment]
Probably they updated srdfdom to 0.6.3, in that case I have to recreate the docker images and rebuild the packages. I can do that tonight.

**Comment by elpimous** [comment]
Correct : ros-noetic-srdfdom_0.6.3-1
Please add update to ./install.sh too 
Ready to test 
Thanks

**Comment by graiola** [comment]
Fixed with 0.0.8

**Comment by elpimous** [comment]
Hello Gennaro.Je cherche à tester wolf_navigation, et je rencontre quelques difficultés...Peux tu m expliquer comment tester wolf_localisation ?Je lance wolf_localisation, avec le world office, puis le service standup, puis spot planté et pas de mappingBonne journée

**Comment by graiola** [comment]
Could you open an issue on wolf_navigation? Thank you.
