### ISSUE TITLE
working errors on ubuntu20.04/noetic

### ISSUE THREAD

**Issue by elpimous** [graiola/wolf-setup#26]
hey guys, working on Ylo2robot, with new ubuntu20.04 working Noetic.
my native python is 3.8

`./install.sh` installed correctly
`
wolf_description` installed correctly

`roslaunch wolf_controller wolf_controller_bringup.launch robot_name:=ylo2 input_device:=keyboard`

```
/usr/bin/env: «python»: Aucun fichier ou dossier de ce type
[goto0-5] process has died [pid 65547, exit code 127, cmd /home/ylo2/catkin_ws/src/wolf_descriptions/wolf_description_utils/scripts/go0
```
installed python, and some python(2) imports are missing!
```
Traceback (most recent call last):
  File "/home/ylo2/catkin_ws/src/wolf_descriptions/wolf_description_utils/scripts/go0", line 3, in <module>
    import rospy, sys, os, time, tf
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_Bool.py", line 6, in <module>
    import genpy
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 48, in <module>
    import yaml
ImportError: No module named yaml
[goto0-5] process has died [pid 1614, exit code 1, cmd /home/ylo2/catkin_ws/src/wolf_descriptions/wolf_description_utils/scripts/go0
```
it seems that i cant install yaml (conflits with pip)

**Comment by EnricoMingo** [comment]
Hi!
Can you try

 sudo apt-get install python3-yaml
?

> Il giorno 20 feb 2022, alle ore 21:24, FOUCAULT Vincent ***@***.***> ha scritto:
> 
> ImportError: No module named yaml

**Comment by EnricoMingo** [comment]
Or first purge and then reinstall 

> Il giorno 20 feb 2022, alle ore 21:31, Enrico Mingo ***@***.***> ha scritto:
> 
> ﻿
> Hi!
> Can you try
> 
>  sudo apt-get install python3-yaml
> ?
> 
>>> Il giorno 20 feb 2022, alle ore 21:24, FOUCAULT Vincent ***@***.***> ha scritto:
>>> 
>> ImportError: No module named yaml

**Comment by elpimous** [comment]
python3-yaml est déjà la version la plus récente (5.3.1-1ubuntu0.1)
already newest version.
You want me to purge the full install ? I'll have same install right after !?!

**Comment by elpimous** [comment]
seems looking for yaml for python2 ?!

**Comment by EnricoMingo** [comment]
Nope, not purge everything.
If you run ipython or a python shell can you import yaml?

> Il giorno 20 feb 2022, alle ore 21:31, Enrico Mingo ***@***.***> ha scritto:
> 
> ﻿
> Hi!
> Can you try
> 
>  sudo apt-get install python3-yaml
> ?
> 
>>> Il giorno 20 feb 2022, alle ore 21:24, FOUCAULT Vincent ***@***.***> ha scritto:
>>> 
>> ImportError: No module named yaml

**Comment by elpimous** [comment]
ImportError: No module named yaml
no

```
ylo2@ylo2-UP-WHL01:~$ sudo python -m pip install pyyaml
/usr/bin/python: No module named pip
```
```
ylo2@ylo2-UP-WHL01:~$ pip install pyyaml
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (5.3.1)
```
```
ylo2@ylo2-UP-WHL01:~$ sudo apt-get install pip
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Note : sélection de « python3-pip » au lieu de « pip »
python3-pip est déjà la version la plus récente (20.0.2-5ubuntu1.6).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
```
```
ylo2@ylo2-UP-WHL01:~$ sudo apt-get install python-pip
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Aucune version du paquet python-pip n'est disponible, mais il existe dans la base
de données. Cela signifie en général que le paquet est manquant, qu'il est devenu obsolète
ou qu'il n'est disponible que sur une autre source
Cependant les paquets suivants le remplacent :
  python3-pip

E: Le paquet « python-pip » n'a pas de version susceptible d'être installée
```

**Comment by EnricoMingo** [comment]
I would say you are missing the package…can you locate it in your machine?

**Comment by graiola** [comment]
With ubuntu 20.04 you should be using python3. I think something got wrong with your python environment :/

**Comment by elpimous** [comment]
hello the team, i saw that i missed the following command after my ROS NOETIC environment installation : 
$ `catkin_make -DPYTHON_EXECUTABLE=/usr/bin/python3`
after that, it was ok.
