### ISSUE TITLE
libmoveit_robot_model.so updated

### ISSUE THREAD

**Issue by itaouil** [graiola/wolf-setup#29]
Hi Gennaro,

I updated my system and the **libmoveit_robot_model.so.1.0.9** library that the controller depends on got updated to 1.0.10.

Would you be able to generate a new version for this update?

Best,
Ilyass

**Comment by graiola** [comment]
Hi Ilyass,

I think the debians in the devel folder are already updated.
Can you try them?

Gennaro

**Comment by itaouil** [comment]
I tried to install using ```./install -b devel``` but I obtain the same error.

![image](https://user-images.githubusercontent.com/17275225/159264971-832544b6-82ce-4f32-a883-883e121c3693.png)

**Comment by graiola** [comment]
Could you tell me which version of wolf_controller you are using?

**Comment by itaouil** [comment]
I am using the latest version (I ultimately updated it some time ago).

![image](https://user-images.githubusercontent.com/17275225/159267234-0b9eb46b-efed-40cd-bee0-c90dba93ab76.png)

**Comment by graiola** [comment]
I started the to regenerate the debians but it is going to take some time unfortunately... They should be updated by this evening.

**Comment by itaouil** [comment]
Ok thanks :)

**Comment by graiola** [comment]
@itaouil the devel debians should be updated. Can you test it? Thanks.

**Comment by itaouil** [comment]
Yes, it works :).

Thanks a lot Gennaro!
