### ISSUE TITLE
missing packages on wolf setup install, on noetic

### ISSUE THREAD

**Issue by elpimous** [graiola/wolf-setup#34]
./install.sh on noetic :+1: 

dpkg: des problèmes de dépendances empêchent la configuration de ros-noetic-wolf-controller :
 ros-noetic-wolf-controller dépend de modelinterfacerbdl (= 1.1.10) ; cependant :
  **Le paquet modelinterfacerbdl n'est pas installé.**
 ros-noetic-wolf-controller dépend de xbotinterface (= 2.1.0-1fe46dc-amd64-focal) ; cependant :
  **Le paquet xbotinterface n'est pas installé.

dpkg: erreur de traitement du paquet ros-noetic-wolf-controller (--install) :**
 problèmes de dépendances - laissé non configuré
Paramétrage de ros-noetic-wolf-description-utils (0.0.1-0focal) ...
Paramétrage de ros-noetic-wolf-exploration (0.0.1-0focal) ...
Paramétrage de ros-noetic-wolf-gazebo-resources (0.0.1-0focal) ...
Paramétrage de ros-noetic-wolf-hardware-interface (0.0.1-0focal) ...
**dpkg: des problèmes de dépendances empêchent la configuration de ros-noetic-wolf-navigation-utils :
 ros-noetic-wolf-navigation-utils dépend de ros-noetic-wolf-controller ; cependant :
 Le paquet ros-noetic-wolf-controller n'est pas encore configuré.**

dpkg: erreur de traitement du paquet ros-noetic-wolf-navigation-utils (--install) :
 problèmes de dépendances - laissé non configuré
Paramétrage de ros-noetic-wolf-rviz-plugin (0.0.1-0focal) ...
Paramétrage de ros-noetic-wolf-waypoints (0.0.1-0focal) ...
Paramétrage de ros-noetic-ylo2-description (0.0.1-0focal) ...
Paramétrage de ros-noetic-anymalc-description (1.0.2-0focal) ...
Paramétrage de ros-noetic-spot-description (0.0.1-0focal) ...
Paramétrage de ros-noetic-wolf-gazebo-interface (0.0.1-0focal) ...
**Des erreurs ont été rencontrées pendant l'exécution :
 ros-noetic-wolf-controller
 ros-noetic-wolf-navigation-utils**

Any idea ??

**Comment by elpimous** [comment]
worked with "git checkout xbot_apt_server" first

**Comment by graiola** [comment]
weird, it should work on the master branch as well... I am going to investigate that. Thank you for reporting the issue :)

**Comment by elpimous** [comment]
you're welcome..
but this error occur, even with a `source ~/.bashrc`
```
[ERROR] [1662061215.418513830]: Could not load class 'wolf_controller/Controller': Failed to load library /opt/ros/noetic/lib/libwolf_controller.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libmatlogger2.so.1.3.1: cannot open shared object file: No such file or directory)
[ERROR] [1662061215.418580017]: Could not load controller 'wolf_controller' because controller type 'wolf_controller/Controller' does not exist.
[ERROR] [1662061215.418608335]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [1662061216.419894, 0.000000]: Failed to load wolf_controller
```

**Comment by graiola** [comment]
Because it is not supposed to work with the xbot_apt_server branch.

**Comment by graiola** [comment]
Can you try again? I just updated the debians and the docker images, and they are working fine for me. Thank you :)

**Comment by elpimous** [comment]
humm, errors ?!!
(i don't use dockers)


https://pastebin.com/ZUfrivuA

**Comment by graiola** [comment]
I think the problem is caused by the xbot apt list. Can you remove the xbot source from your apt list and try to install again?

**Comment by elpimous** [comment]
removed.
same error : 
https://pastebin.com/dZaQkjfA

**Comment by elpimous** [comment]
removed.
same error : https://pastebin.com/XZUYVFKT

**Comment by graiola** [comment]
try to run the `uninstall.sh` script in the `debs/advr` folder and install again

**Comment by elpimous** [comment]
humm. removed from apt,
removed any xbot_*
reinstall ok
under catkin_ws,  `catkin_make`, then `source ~/.bashrc`, then `roslaunch wolf_controller wolf_controller_bringup.launch`
can't find lib : Failed to load library /opt/ros/noetic/lib/libwolf_controller.so

the error : https://pastebin.com/Fts4uhJM

my ~/.bashrc : 

`...
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

source /opt/ros/noetic/setup.bash
source /home/predator/catkin_ws/devel/setup.bash
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/opt/ros/noetic/share/wolf_gazebo_resources/models
source /opt/xbot/setup.sh`

ok

**Comment by elpimous** [comment]
==> try to run the uninstall.sh script in the debs/advr folder and install again
  working !!
Thanks Gennaro.
