### ISSUE TITLE
Changing initial stand_down pose

### ISSUE THREAD

**Issue by elpimous** [graiola/wolf-setup#36]
Hey, where to change the initial robot joints pose ?
Could it be possible to integrate it into robot_name_description/params/robot_name_params.xml ?

**Comment by robolableonardo** [comment]
Hello, to change the stand down posture you can edit this file:

https://github.com/graiola/wolf_descriptions/blob/master/ylo2_description/robots/ylo2.srdf.xacro#L66-L78

**Comment by elpimous** [comment]
Thanks friend
