### ISSUE TITLE
Criteria that defines moving feet pair from idle position

### ISSUE THREAD

**Issue by itaouil** [graiola/wolf-setup#9]
Hi @graiola,

I noticed that when I send motion commands to the robot when this one is static it can either start its motion with the right or left front foot.

Is this decision based on some criteria? Maybe the foot that is most in the front starts?

Best,
Ilyass

**Comment by graiola** [comment]
the order which the feet are scheduled when trotting is the following: LF RH and RF LH and it should remain the same all the time.

What is the problem you are experiencing?

**Comment by itaouil** [comment]
Yes yes you are right.

I phrased my question wrong I guess.

What is the criteria that defines which set of feet starts the motion starting from an idle position (by pairs I mean LF/RH or RF/LH). Cause from I could see both pairs can start equally. Right?

**Comment by graiola** [comment]
The order is cyclic, so it starts with LF RH, then when both feet are in contact the scheduler moves to the next pair RF LH, and it repeats...

**Comment by itaouil** [comment]
Thanks for the input! :)
